/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ecosimulator;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
      System.out.println("Eita");
    }
}
